# Local development compose - uses Neon PostgreSQL (no local postgres)
# Usage: docker compose -f compose.local.yaml up

services:
  agent_service:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    network_mode: "host"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8180/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./privatecredentials:/privatecredentials
    develop:
      watch:
        - path: src/agents/
          action: sync+restart
          target: /app/agents/
        - path: src/schema/
          action: sync+restart
          target: /app/schema/
        - path: src/service/
          action: sync+restart
          target: /app/service/
        - path: src/core/
          action: sync+restart
          target: /app/core/
        - path: src/memory/
          action: sync+restart
          target: /app/memory/
        - path: src/ai_agents/
          action: sync+restart
          target: /app/ai_agents/
