version: "3.7"
services:

## --------------------------- AGENT SERVICE --------------------------- ##

  agent-service:
    image: ghcr.io/${GITHUB_REPOSITORY:-pedrohnas0/agent-service-toolkit}:${IMAGE_TAG:-latest}

    networks:
      - network

    environment:
      ## Server
      - HOST=0.0.0.0
      - PORT=8080
      - MODE=production

      ## Database (Neon)
      - DATABASE_TYPE=postgres
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=npg_KspCF8jH4JWI
      - POSTGRES_HOST=ep-blue-base-acjz30d5-pooler.sa-east-1.aws.neon.tech
      - POSTGRES_PORT=5432
      - POSTGRES_DB=neondb
      - POSTGRES_MIN_CONNECTIONS_PER_POOL=1
      - POSTGRES_MAX_CONNECTIONS_PER_POOL=5

      ## Auth
      - AUTH_SECRET=${AUTH_SECRET}

      ## LLM Providers
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gpt-4o}

      ## Observability
      - LANGSMITH_TRACING=${LANGSMITH_TRACING:-true}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-agent-service-prod}

      ## Timezone
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2"
          memory: 2048M
      labels:
        - traefik.enable=true
        - traefik.http.routers.agent-service.rule=Host(`agent.buildzero.ai`)
        - traefik.http.services.agent-service.loadbalancer.server.port=8080
        - traefik.http.routers.agent-service.service=agent-service
        - traefik.http.routers.agent-service.tls.certresolver=letsencryptresolver
        - traefik.http.routers.agent-service.entrypoints=websecure
        - traefik.http.routers.agent-service.tls=true

## --------------------------- AGENT SERVICE --------------------------- ##

networks:
  network:
    name: network
    external: true
